#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: e36a856
#
# Source0 file verified with key 0x2D4E1FE95957135D (stefankangas@gmail.com)
#
Name     : emacs-x11
Version  : 30.1
Release  : 86
URL      : https://ftpmirror.gnu.org/emacs/emacs-30.1.tar.xz
Source0  : https://ftpmirror.gnu.org/emacs/emacs-30.1.tar.xz
Source1  : https://ftpmirror.gnu.org/emacs/emacs-30.1.tar.xz.sig
Source2  : 2D4E1FE95957135D.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: emacs-x11-bin = %{version}-%{release}
Requires: emacs-x11-data = %{version}-%{release}
Requires: emacs-x11-libexec = %{version}-%{release}
Requires: emacs-x11-license = %{version}-%{release}
Requires: emacs = %{version}
BuildRequires : ImageMagick-dev
BuildRequires : acl-dev
BuildRequires : alsa-lib-dev
BuildRequires : buildreq-configure
BuildRequires : gmp-dev
BuildRequires : gnupg
BuildRequires : gnutls-dev
BuildRequires : gpm-dev
BuildRequires : gtk3-dev
BuildRequires : jansson-dev
BuildRequires : lcms2-dev
BuildRequires : libXfixes-dev
BuildRequires : libXinerama-dev
BuildRequires : libXrandr-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : librsvg-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(sm)
BuildRequires : pkgconfig(xpm)
BuildRequires : systemd-dev
BuildRequires : texinfo
BuildRequires : tree-sitter-dev
BuildRequires : valgrind
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Don-t-fingerprint-the-pdmp-file.patch

%description
See the end of the file for license conditions.
This directory tree holds version 30.1 of GNU Emacs, the extensible,
customizable, self-documenting real-time display editor.

%package bin
Summary: bin components for the emacs-x11 package.
Group: Binaries
Requires: emacs-x11-data = %{version}-%{release}
Requires: emacs-x11-libexec = %{version}-%{release}
Requires: emacs-x11-license = %{version}-%{release}

%description bin
bin components for the emacs-x11 package.


%package data
Summary: data components for the emacs-x11 package.
Group: Data

%description data
data components for the emacs-x11 package.


%package libexec
Summary: libexec components for the emacs-x11 package.
Group: Default
Requires: emacs-x11-license = %{version}-%{release}

%description libexec
libexec components for the emacs-x11 package.


%package license
Summary: license components for the emacs-x11 package.
Group: Default

%description license
license components for the emacs-x11 package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 2D4E1FE95957135D' gpg.status
%setup -q -n emacs-30.1
cd %{_builddir}/emacs-30.1
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1740598432
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --without-m17n-flt \
--without-libotf \
--without-xaw3d \
--with-xpm=yes \
--with-gif=no \
--with-tiff=no \
--with-imagemagick \
--with-modules \
--enable-link-time-optimization \
--with-cairo
make  %{?_smp_mflags}

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1740598432
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/emacs-x11
cp %{_builddir}/emacs-%{version}/COPYING %{buildroot}/usr/share/package-licenses/emacs-x11/31a3d460bb3c7d98845187c716a30db81c44b615 || :
cp %{_builddir}/emacs-%{version}/etc/COPYING %{buildroot}/usr/share/package-licenses/emacs-x11/31a3d460bb3c7d98845187c716a30db81c44b615 || :
cp %{_builddir}/emacs-%{version}/leim/COPYING %{buildroot}/usr/share/package-licenses/emacs-x11/31a3d460bb3c7d98845187c716a30db81c44b615 || :
cp %{_builddir}/emacs-%{version}/lib-src/COPYING %{buildroot}/usr/share/package-licenses/emacs-x11/31a3d460bb3c7d98845187c716a30db81c44b615 || :
cp %{_builddir}/emacs-%{version}/lib/COPYING %{buildroot}/usr/share/package-licenses/emacs-x11/31a3d460bb3c7d98845187c716a30db81c44b615 || :
cp %{_builddir}/emacs-%{version}/lisp/COPYING %{buildroot}/usr/share/package-licenses/emacs-x11/31a3d460bb3c7d98845187c716a30db81c44b615 || :
cp %{_builddir}/emacs-%{version}/lwlib/COPYING %{buildroot}/usr/share/package-licenses/emacs-x11/31a3d460bb3c7d98845187c716a30db81c44b615 || :
cp %{_builddir}/emacs-%{version}/msdos/COPYING %{buildroot}/usr/share/package-licenses/emacs-x11/31a3d460bb3c7d98845187c716a30db81c44b615 || :
cp %{_builddir}/emacs-%{version}/nt/COPYING %{buildroot}/usr/share/package-licenses/emacs-x11/31a3d460bb3c7d98845187c716a30db81c44b615 || :
cp %{_builddir}/emacs-%{version}/src/COPYING %{buildroot}/usr/share/package-licenses/emacs-x11/31a3d460bb3c7d98845187c716a30db81c44b615 || :
export GOAMD64=v2
GOAMD64=v2
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/bin/ctags
rm -f %{buildroot}*/usr/bin/ebrowse
rm -f %{buildroot}*/usr/bin/emacsclient
rm -f %{buildroot}*/usr/bin/etags
rm -f %{buildroot}*/usr/bin/grep-changelog
rm -f %{buildroot}*/usr/include/emacs-module.h
rm -f %{buildroot}*/usr/lib64/systemd/user/emacs.service
rm -f %{buildroot}*/usr/share/appdata/emacs.appdata.xml
rm -f %{buildroot}*/usr/share/metainfo/emacs.appdata.xml
rm -f %{buildroot}*/var/games/emacs/snake-scores
rm -f %{buildroot}*/var/games/emacs/tetris-scores
rm -f %{buildroot}*/usr/share/metainfo/emacs.metainfo.xml
## install_append content
# pdmp files are required for emacs operation
find %{buildroot}/usr/libexec/emacs -type f ! -name '*.pdmp' -delete
find %{buildroot}/usr/libexec/emacs -type l -delete
rm -rf %{buildroot}*/usr/share/emacs
rm -rf %{buildroot}*/usr/share/icons
rm -rf %{buildroot}*/usr/share/info
rm -rf %{buildroot}*/usr/share/man
emacsbin=$(realpath -e %{buildroot}/usr/bin/emacs)
mv "$emacsbin" %{buildroot}/usr/bin/emacs-x11
pdmp_file="$(basename %{buildroot}/usr/libexec/emacs/%version/x86_64-generic-linux-gnu/emacs-*.pdmp)"
fingerprint="${pdmp_file#emacs-}"
mv %{buildroot}/usr/libexec/emacs/%version/x86_64-generic-linux-gnu/emacs-*.pdmp %{buildroot}/usr/libexec/emacs/%version/x86_64-generic-linux-gnu/emacs-x11-"${fingerprint}"
ln -s emacs-x11-"${fingerprint}" %{buildroot}/usr/libexec/emacs/%version/x86_64-generic-linux-gnu/emacs-x11.pdmp
rm %{buildroot}*/usr/bin/emacs
sed -i 's/Exec=emacs/Exec=emacs-x11/' %{buildroot}/usr/share/applications/emacs.desktop
ln -s emacs-x11 %{buildroot}/usr/bin/xemacs
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/byte-opt-9c5f25f5-5065798b.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/bytecomp-12882072-55673a29.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/charscript-600dca1a-b361c995.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/comp-7672a6ed-a60aebab.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/comp-common-6e17f702-570d32c2.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/comp-cstr-ef162ef7-e12f80ed.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/comp-run-a15747ee-6eeac0b4.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/emoji-zwj-4f682c68-0cae7999.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/abbrev-2af30c9a-0abc0b83.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/android-win-ae89b9ba-f7987183.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/backquote-d5b20f7c-b40ce9d5.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/bindings-d30713c5-6c4266e3.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/buff-menu-da4b0b04-5728eaa1.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/burmese-3ddca72e-6aa09761.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/button-747c9d6e-1f96a3b1.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/byte-run-79ff048e-e0a661b8.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/case-table-3a8e2808-f90bfbf9.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/cconv-3b1f1f98-e533377e.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/cham-7498ab67-4831a6b4.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/characters-45232aae-1d7bb527.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/chinese-c5896779-e8a0435d.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/cl-generic-be68ad15-b151f19c.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/cl-preloaded-6e6a1f4e-b7e4c17d.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/common-win-4b869e38-f044a289.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/composite-beea1fd5-44285ec1.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/cp51932-89105e97-e8997b76.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/cus-face-74f1689e-c2052542.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/cus-start-26315480-3fc487b4.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/custom-c166a157-388d7692.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/cyrillic-79ea53dc-4897893b.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/czech-c6790aeb-02622b50.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/debug-early-d734b212-85942f44.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/disp-table-375616aa-2e22450a.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/dnd-12d90309-5850bd88.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/dos-fns-6e9410f2-0c776fe5.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/dos-vars-f5506e15-2f6b7169.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/dos-w32-923cbfb1-a407fb0c.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/dynamic-setting-55f80457-c5508289.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/easymenu-1fb41c0e-d46de055.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/ediff-hook-0b92f1a2-d72378b3.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/eldoc-d20a5fe9-9ffa2935.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/electric-a9ca6cdd-16dd18c6.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/elisp-mode-90dbfe40-76aacd01.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/english-e3896aa2-87422f55.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/env-72406999-4c053f3e.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/epa-hook-99ab3afb-8b6b219b.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/ethiopic-b0f5a6d8-4d1d8675.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/eucjp-ms-5daf4e1a-cf27da4c.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/european-369de593-5567801a.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/faces-b9447c93-62def449.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/files-1e8937b2-77d08b11.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/fill-19d89c43-31bbb91e.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/float-sup-c5369b32-ffd3632a.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/font-core-c3bff1fd-d1e13c61.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/font-lock-895216f6-dbd5a4a0.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/fontset-da863153-827cdb3f.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/format-c5b23b0d-e30372f6.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/frame-b40fc590-a1371df0.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/fringe-d5d49a60-76f77046.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/georgian-8daa6ed6-2096a858.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/greek-ddbf878c-592da1c1.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/haiku-win-a742f47b-dd586fa2.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/hebrew-b9ed6a0d-1b7412cc.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/help-59d8049f-3a1542fb.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/image-f221b419-1c1dc97c.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/indent-396b3792-a4a601d1.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/indian-0c4ce628-31a8f542.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/indonesian-3fd5df38-d3dcdd20.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/internal-957edb14-921007ec.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/isearch-693bdd75-080495e7.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/iso-transl-466860a2-5f91a072.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/japanese-d54f685c-59263e31.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/jit-lock-8a988e43-86e09700.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/jka-cmpr-hook-ff630d3e-edeb1ede.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/keymap-b4249274-c53ed737.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/khmer-914ba26a-faa77228.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/korean-2f82396a-d337cc16.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/lao-81d6a353-969cf33a.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/lisp-1e88867d-54c570c0.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/lisp-mode-410874a4-c4359be2.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/ls-lisp-4d1ed918-aa9dbb10.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/macroexp-2c3e1495-4fd39378.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/map-ynp-990591b5-3378378d.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/menu-bar-4f46ea94-811c6ef8.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/minibuffer-1b0f548b-5fadde34.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/misc-lang-7cb33d20-b1246a9e.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/mouse-15f283fa-232e6965.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/mule-3352613d-d3b3728f.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/mule-cmds-c8553014-baf12bd2.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/mule-conf-eca41db8-3543469d.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/mule-util-5c349a87-f8e07e95.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/mwheel-168e9ec3-fed95d15.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/nadvice-64630aaa-cd5d6bd0.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/newcomment-678006bb-9e10fc1b.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/ns-win-ef8075c0-bedfd65c.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/obarray-318a5d56-6aca5f51.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/oclosure-b279097d-192f7d24.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/page-ee7241cc-be0ce2a8.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/paragraphs-faf2e9b4-b469a638.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/paren-0f414553-42e5d843.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/pc-win-2c50182f-18d6ccb2.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/pgtk-dnd-6859c677-856161c2.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/pgtk-win-9e6b24f1-5e4ab307.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/philippine-8a94d8f7-47b599bf.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/prog-mode-642b2411-78121acd.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/regexp-opt-d2355c94-95336c0a.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/register-80045398-b4807f81.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/replace-fc551dbc-830f0d51.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/rfn-eshadow-25788e78-6fe1678f.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/rmc-9c382b5d-7a1ad893.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/romanian-36a52030-e1f93cf7.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/scroll-bar-20650688-8f44cc8e.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/select-784d9bb7-fc9c67e6.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/seq-c314b42f-749b3396.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/shorthands-1dc1e95e-c6f86d1e.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/simple-fab5b0cf-4a9a0458.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/sinhala-ce98fc4b-bbda3c41.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/slovak-ece02e01-7ea0846d.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/startup-bbc6ea72-bc20aae4.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/subr-13adf6a6-7158519c.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/syntax-bf4e4bc4-bb2977b6.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/tab-bar-f81d329c-71616fa7.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/tabulated-list-552ba1e5-67cbcb20.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/tai-viet-fdaa77d1-aa7821cb.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/text-mode-7f741068-feecd4fd.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/thai-7d4342b5-ae7f22b1.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/tibetan-b792461b-c7d573c8.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/timer-3ee7cfd9-ae4e9eed.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/tool-bar-ae0b5bc0-9dacbbde.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/tooltip-29462ede-511bee00.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/touch-screen-80a26276-ac0e7c7b.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/tty-colors-b7804baf-847106c0.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/ucs-normalize-ad11ce47-ec515eda.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/uniquify-0fb233ac-80636165.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/utf-8-lang-7d52ad20-7889d202.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/vc-hooks-cfa0878e-ed52d67e.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/version-025f5cb3-b763f236.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/vietnamese-f823b5c7-2ff7ae8c.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/w32-fns-d8ead36c-b59184c2.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/w32-vars-6533c316-014dfb78.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/w32-win-a6781510-046ab8b4.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/widget-5b69ebb0-99e8ea6d.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/window-0d1b8b93-70443922.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/x-dnd-f8192910-fea7ea32.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/preloaded/x-win-3c49581f-91aa60b5.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/subr--trampoline-68616e646c652d736176652d73657373696f6e_handle_save_session_0.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/subr--trampoline-6d6163726f657870616e64_macroexpand_0.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/subr--trampoline-782d626567696e2d64726167_x_begin_drag_0.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/subr--trampoline-782d646973706c61792d6261636b696e672d73746f7265_x_display_backing_store_0.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/subr--trampoline-782d646973706c61792d636f6c6f722d63656c6c73_x_display_color_cells_0.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/subr--trampoline-782d646973706c61792d6d6d2d686569676874_x_display_mm_height_0.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/subr--trampoline-782d646973706c61792d6d6d2d7769647468_x_display_mm_width_0.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/subr--trampoline-782d646973706c61792d706978656c2d686569676874_x_display_pixel_height_0.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/subr--trampoline-782d646973706c61792d706978656c2d7769647468_x_display_pixel_width_0.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/subr--trampoline-782d646973706c61792d706c616e6573_x_display_planes_0.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/subr--trampoline-782d646973706c61792d73637265656e73_x_display_screens_0.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/subr--trampoline-782d646973706c61792d76697375616c2d636c617373_x_display_visual_class_0.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/subr--trampoline-782d66696c652d6469616c6f67_x_file_dialog_0.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/subr--trampoline-782d6c6973742d666f6e7473_x_list_fonts_0.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/subr--trampoline-782d7365727665722d6d61782d726571756573742d73697a65_x_server_max_request_size_0.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/subr--trampoline-782d7365727665722d76656e646f72_x_server_vendor_0.eln
/usr/lib64/emacs/30.1/native-lisp/30.1-05a1f85c/subr--trampoline-782d7365727665722d76657273696f6e_x_server_version_0.eln

%files bin
%defattr(-,root,root,-)
/usr/bin/emacs-x11
/usr/bin/xemacs

%files data
%defattr(-,root,root,-)
/usr/share/applications/emacs-mail.desktop
/usr/share/applications/emacs.desktop
/usr/share/applications/emacsclient-mail.desktop
/usr/share/applications/emacsclient.desktop

%files libexec
%defattr(-,root,root,-)
/usr/libexec/emacs/30.1/x86_64-generic-linux-gnu/emacs-x11-30.1.pdmp
/usr/libexec/emacs/30.1/x86_64-generic-linux-gnu/emacs-x11.pdmp

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/emacs-x11/31a3d460bb3c7d98845187c716a30db81c44b615
